baseURL = "/"
languageCode = "en-us"
title = "Annie Zean Dunbar"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "dunbar.annie@gmail.com "
    facebook = ""
    twitter = "lexiscollado"
    linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"

[params.nav]
    enable = true

[params.hero]
    enable = true
    title = "About"
    avatar = "uploads/zean-avatar-cropped.png"
    subtitle = "Welcome! Bienvenu! Annie Zean Dunbar is a Liberian-American writer, educator, and social worker living in Chicago, IL."
    hero_right = ["**Annie Zean Dunbar is an educator and social worker, and has worked in multicultural communities as a program manager, survey researcher, and case manager.**",
                  "Her research interests include race and identity formation, trauma and reconciliation, secondary migration, and long term refugee and migrant resettlement in the United States.  Zean’s creative writing centers community conceptions of truth and omission, the liminal space between understanding self and others, and an examination of memory. She is a cofounder of Connect-the- Dots, an arts based organization focused on examining social constructs and human connection. Zean is a graduate from the Social Service Administration at the University of Chicago with a program of study in International Social Welfare. Annie Zean is a 2014 Fellow of the Pozen Family Center for Human Rights at the University of Chicago, and holds certificate in Forced Migration from Center for Refugee Studies at York University and Refugee Protection and the Rights and Process of (Re)Settlement through the Center for Forced Migration Studies. As a Human Rights Fellow for the Pozen Family Center for Human Rights, Annie Zean was deployed to Monrovia, Liberia during the summer of 2014.  Her fellowship was designed to educate women in Monrovia on the upcoming election and improve voter registration and participation.  Because of the Ebola outbreak, she was reassigned to the Social Mobilization team to survey community members on their understanding of the Ebola risks and provide outreach and education to community members to improve compliance with public health directives. She is the Social Media Lead for the Emerging Scholars and Practitioner on Migration Issues (ESPMI) Network. Zean would describe herself as a post-goth black woman, perpetual optimist, with an affinity for commas, sing alongs, and referential humor."]
    resume = "ResumeCollado.pdf"

[params.cv]
    title = 'CV'

[params.work]
    title = "Work"

[params.contact]
    enable = true
    title = "Contact"
    subtitle = "Get in touch"

[params.footer]
    enable = true
