backend:
  name: git-gateway
  branch: master
media_folder: "site/static/img/uploads"
public_folder: "img/uploads"
collections:
- name: "pages"
  label: "Pages"
  files:
    - file: "site/content/hero/_index.md"
      label: "About Section"
      name: "hero"
      fields:
        - {label: Blurb, name: blurb, widget: string}
        - {label: About Intro, name: intro, widget: string}
        - {label: About Body, name: body, widget: string}
