backend:
  name: git-gateway
  branch: master
media_folder: "site/static/uploads"
public_folder: "uploads"
collections:
- name: "sections"
  label: "Sections"
  files:
    - file: "site/content/_index.md"
      label: "Main"
      name: "main"
      fields:
        - {label: "About", name: about, widget: object, fields: [
            {label: Blurb, name: blurb, widget: string},
            {label: About, name: about, widget: markdown},
            {label: Avatar, name: avatar, hint: "please make sure uploaded image is square, i.e. height to width ratio is 1:1", widget: image}]}
        - {label: "Contact Info", name: contact, widget: object, fields: [
            {label: Address, name: address, widget: markdown},
            {label: Email, name: email, widget: string},
            {label: "Phone Number", name: phone, widget: string}]}
        - {label: "Social Media*", name: social, widget: object, hint: "*to hide the icon link for one of the URLs on the site, leave the corresponding field blank", fields: [
            {label: "Twitter URL", name: twitter, widget: string},
            {label: "LinkedIn URL", name: linkedin, widget: string},
            {label: "Wordpress URL", name: wordpress, widget: string},
            {label: "DU Portfolio URL", name: du_portfolio, widget: string}
        ]}
        - {label: "CV File", name: cv, widget: file}
    - file: "site/content/cv.md"
      label: "CV"
      name: "cv"
      fields:
        - {label: "CV Order", name: "cv_order", widget: "list", allow_add: false, hint: "*drag and drop the section names to change the order in which they will appear on the site", fields: [
            {label: Section Name, name: section_name, widget: string}
        ]}
        - {label: "Education", name: education, widget: list, fields: [
            {label: University, name: university, widget: string}, 
            {label: "School/Department", name: school, widget: string, required: false}, 
            {label: "Degree Earned", name: degree, widget: string}, 
            {label: "Date Earned/Expected", name: date, widget: string}, 
            {label: "Additional Details", name: details, widget: string, required: false}]}
        - {label: "Research Interests", name: research_interests, widget: list}
        - {label: "Teaching Interests", name: teaching_interests, widget: list, fields: [{label: Interest, name: interest, widget: string}]}
        - {label: "Research Experience", name: research_experience, widget: list, fields: [
            {label: Name, name: name, widget: string},
            {label: "Contact(s)", name: contact, widget: string},
            {label: Position, name: position, widget: string},
            {label: Date, name: date, widget: string},
            {label: Details, name: details, widget: markdown}
        ]}
        - {label: "Grants and Fellowships", name: grants, widget: list, fields: [
            {label: Name, name: name, widget: string},
            {label: Details, name: details, widget: string}
        ]}
        - {label: "Peer Reviewed Publications", name: pubs, widget: list, field: {label: Publication, name: pub, widget: markdown}}
        - {label: "Artistic Publications", name: art_pubs, widget: list, field: {label: Publication, name: pub, widget: markdown}}
        - {label: "Peer Reviewed Presentations", name: presentations, widget: list, fields: [
            {label: Presentation, name: presentation, widget: markdown},
            {label: Date, name: date, widget: string}
          ]}
        - {label: "Invited Presentations", name: invited_presentations, widget: list, fields: [
            {label: Presentation, name: presentation, widget: markdown},
            {label: Date, name: date, widget: string}
          ]}
        - {label: "Teaching Experience", name: teaching_exp, widget: list, fields: [
            {label: Location, name: location, widget: string},
            {label: Position, name: position, widget: string},
            {label: Date, name: date, widget: string},
            {label: Details, name: details, widget: string}
        ]}
        - {label: "Other Professional Experience", name: professional_exp, widget: list, fields: [
            {label: Organization, name: organization, widget: string},
            {label: Position, name: position, widget: string},
            {label: Date, name: date, widget: string},
            {label: Details, name: details, widget: list, field: {label: Detail, name: detail, widget: string}}
        ]}
        - {label: Service, name: service, widget: list, fields: [
          {label: Organization, name: organization, widget: string},
          {label: Position, name: position, widget: string},
          {label: Date, name: date, widget: string},
          {label: Details, name: details, widget: list, field: {label: Detail, name: detail, widget: string}}
        ]}
        - {label: Training, name: training, widget: list, fields: [
            {label: Organization, name: organization, widget: string},
            {label: Program, name: program, widget: string}]}
        - {label: Memberships, name: memberships, widget: list}
- name: "work"
  label: "Work"
  folder: "site/content/work"
  create: true
  fields: 
    - {label: Title, name: title, widget: string}
    - {label: Description, name: description, widget: markdown, required: false}
    - {label: Date, name: item_date, widget: string, required: false}
    - {label: Content, name: body, widget: markdown, required: false}
    - {label: Images, name: images, widget: list, fields: [
          {label: Image, name: image, widget: image}]}
    - {label: Paper, name: is_paper, widget: boolean, default: false, required: false}
    - {label: "Artist Project", name: is_artist_project, widget: boolean, default: false, required: false}