backend:
  name: git-gateway
  branch: master
media_folder: "site/static/img/uploads"
public_folder: "img/uploads"
collections:
- name: "pages"
  label: "Pages"
  files:
    - file: "site/content/_index.md"
      label: "Main"
      name: "main"
      fields:
        - {label: "About", name: about, widget: object, fields: [
            {label: Blurb, name: blurb, widget: string},
            {label: About, name: about, widget: markdown},
            {label: Avatar, name: avatar, widget: image}]}
        - {label: "Contact Info", name: contact, widget: object, fields: [
            {label: Address, name: address, widget: markdown},
            {label: Email, name: email, widget: string},
            {label: "Phone Number", name: phone, widget: string}]}
        - {label: "Social Media", name: social, widget: object, fields: [
            {label: "Twitter Username", name: twitter, widget: string},
            {label: "LinkedIn URL", name: linkedin, widget: string},
            {label: "Wordpress URL", name: wordpress, widget: string}
        ]}
    - file: "site/content/cv.md"
      label: "CV"
      name: "cv"
      fields:
        - {label: "Education", name: education, widget: list, fields: [{label: University, name: university, widget: string}, {label: "School/Department", name: school, widget: string}, {label: "Degree Earned", name: degree, widget: string}, {label: "Additional Details", name: details, widget: string}]}
        
