backend:
  name: git-gateway
  branch: master
media_folder: "site/static/img/uploads"
public_folder: "img/uploads"
collections:
- name: "pages"
  label: "Pages"
  files:
    - file: "site/content/_index.md"
      label: "Main"
      name: "main"
      fields:
        - {label: "About", name: about, widget: object, fields: [
            {label: Blurb, name: blurb, widget: string},
            {label: About, name: about, widget: markdown}]}
